### ISSUE TITLE
Better error messaging, is Panic for command not found the right thing?

### ISSUE THREAD

**Issue by aphillipo** [alco/goon#9]
Should goon really panic when the command it was mean to run is not found?  The panic confused me when I was looking at my logs and I don't see the:

```
panic: exec: "someprogram": executable file not found in $PATH
```

Here is what I get instead:

```
panic: write |1: broken pipe


goroutine 3 [running]:
runtime.panic(0xa4ba0, 0xc21001e400)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/runtime/panic.c:266 +0xb6
log.(*Logger).Panicf(0xc21001f190, 0xde260, 0x3, 0x40fe38, 0x1, ...)
	/usr/local/Cellar/go/1.2.2/libexec/src/pkg/log/log.go:200 +0xbd
main.fatal_if(0xc2840, 0xc2100385d0)
	/Users/alco/extra/goworkspace/src/goon/util.go:38 +0x17e
main.inLoop2(0x257388, 0xc2100384b0, 0xc210020140, 0x257310, 0xc210000000, ...)
	/Users/alco/extra/goworkspace/src/goon/io.go:100 +0x5ce
created by main.wrapStdin2
	/Users/alco/extra/goworkspace/src/goon/io.go:25 +0x15a

goroutine 1 [chan receive]:
main.proto_2_0(0x7fff5fbf0101, 0xe3fc0, 0x3, 0xde7a0, 0x1, ...)
	/Users/alco/extra/goworkspace/src/goon/proto_2_0.go:58 +0x3a3
main.main()
	/Users/alco/extra/goworkspace/src/goon/main.go:51 +0x3b6
```

Thanks!

**Comment by alco** [comment]
This has to be improved. Thanks for the report!
